defaults:
  - _self_

d_x: 30 # 7+7+16
d_model: 256
nblocks: 3
resblock_dropout: 0.0
transformer_num_heads: 8
transformer_dim_head: 64
transformer_dropout: 0.1
transformer_depth: 2
transformer_mult_ff: 2
context_dim: 288 # 256+32
use_position_embedding: true
time_embed_mult: 2
